Traceback (most recent call last):
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/qad/anaconda3/envs/dsc/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%R
library(klaR)
feature.names.tg<-gsub("â€™", "'", feature.names.tg)
colnames(feature.table.tg)<-feature.names.tg
vars<-stepclass(feature.table.tg, metadata.table.tg[,1], method="lda", improvement=0.0001)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRRuntimeError[0m                             Traceback (most recent call last)
[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/rpy2/ipython/rmagic.py[0m in [0;36meval[0;34m(self, code)[0m
[1;32m    401[0m                 value, visible = ri.evalr_expr_with_visible(
[0;32m--> 402[0;31m                     [0mr_expr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    403[0m                 )

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/rpy2/rinterface.py[0m in [0;36mevalr_expr_with_visible[0;34m(expr, envir)[0m
[1;32m    195[0m         [0;32mif[0m [0merror_occured[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 196[0;31m             [0;32mraise[0m [0membedded[0m[0;34m.[0m[0mRRuntimeError[0m[0;34m([0m[0m_rinterface[0m[0;34m.[0m[0m_geterrmessage[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    197[0m         [0mres[0m [0;34m=[0m [0mconversion[0m[0;34m.[0m[0m_cdata_to_rinterface[0m[0;34m([0m[0mr_res[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mRRuntimeError[0m: Error in str2lang(x) : <text>:1:42: unexpected INCOMPLETE_STRING
1: metadata.table.tg[, 1] ~  i + me+ an+ he+'t +e w+ ca+ou +wha+ do+ al
                                             ^


During handling of the above exception, another exception occurred:

[0;31mRInterpreterError[0m                         Traceback (most recent call last)
[0;32m/var/folders/3r/55b5kjpd4s14_tg80r24vs7r0000gq/T/ipykernel_97076/279820211.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_cell_magic[0m[0;34m([0m[0;34m'R'[0m[0;34m,[0m [0;34m''[0m[0;34m,[0m [0;34m'library(klaR)\nfeature.names.tg<-gsub("â€™", "\'", feature.names.tg)\ncolnames(feature.table.tg)<-feature.names.tg\nvars<-stepclass(feature.table.tg, metadata.table.tg[,1], method="lda", improvement=0.0001)\n'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/IPython/core/interactiveshell.py[0m in [0;36mrun_cell_magic[0;34m(self, magic_name, line, cell)[0m
[1;32m   2471[0m             [0;32mwith[0m [0mself[0m[0;34m.[0m[0mbuiltin_trap[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2472[0m                 [0margs[0m [0;34m=[0m [0;34m([0m[0mmagic_arg_s[0m[0;34m,[0m [0mcell[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2473[0;31m                 [0mresult[0m [0;34m=[0m [0mfn[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2474[0m             [0;32mreturn[0m [0mresult[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2475[0m [0;34m[0m[0m

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/decorator.py[0m in [0;36mfun[0;34m(*args, **kw)[0m
[1;32m    230[0m             [0;32mif[0m [0;32mnot[0m [0mkwsyntax[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    231[0m                 [0margs[0m[0;34m,[0m [0mkw[0m [0;34m=[0m [0mfix[0m[0;34m([0m[0margs[0m[0;34m,[0m [0mkw[0m[0;34m,[0m [0msig[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 232[0;31m             [0;32mreturn[0m [0mcaller[0m[0;34m([0m[0mfunc[0m[0;34m,[0m [0;34m*[0m[0;34m([0m[0mextras[0m [0;34m+[0m [0margs[0m[0;34m)[0m[0;34m,[0m [0;34m**[0m[0mkw[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    233[0m     [0mfun[0m[0;34m.[0m[0m__name__[0m [0;34m=[0m [0mfunc[0m[0;34m.[0m[0m__name__[0m[0;34m[0m[0;34m[0m[0m
[1;32m    234[0m     [0mfun[0m[0;34m.[0m[0m__doc__[0m [0;34m=[0m [0mfunc[0m[0;34m.[0m[0m__doc__[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/IPython/core/magic.py[0m in [0;36m<lambda>[0;34m(f, *a, **k)[0m
[1;32m    185[0m     [0;31m# but it's overkill for just that one bit of state.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    186[0m     [0;32mdef[0m [0mmagic_deco[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 187[0;31m         [0mcall[0m [0;34m=[0m [0;32mlambda[0m [0mf[0m[0;34m,[0m [0;34m*[0m[0ma[0m[0;34m,[0m [0;34m**[0m[0mk[0m[0;34m:[0m [0mf[0m[0;34m([0m[0;34m*[0m[0ma[0m[0;34m,[0m [0;34m**[0m[0mk[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    188[0m [0;34m[0m[0m
[1;32m    189[0m         [0;32mif[0m [0mcallable[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/rpy2/ipython/rmagic.py[0m in [0;36mR[0;34m(self, line, cell, local_ns)[0m
[1;32m    976[0m             [0;32mif[0m [0;32mnot[0m [0me[0m[0;34m.[0m[0mstdout[0m[0;34m.[0m[0mendswith[0m[0;34m([0m[0me[0m[0;34m.[0m[0merr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    977[0m                 [0mprint[0m[0;34m([0m[0me[0m[0;34m.[0m[0merr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 978[0;31m             [0;32mraise[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    979[0m         [0;32mfinally[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    980[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0mdevice[0m [0;32min[0m [0mDEVICES_STATIC[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/rpy2/ipython/rmagic.py[0m in [0;36mR[0;34m(self, line, cell, local_ns)[0m
[1;32m    941[0m                     [0mreturn_output[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m
[1;32m    942[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 943[0;31m                 [0mtext_result[0m[0;34m,[0m [0mresult[0m[0;34m,[0m [0mvisible[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0meval[0m[0;34m([0m[0mcode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    944[0m                 [0mtext_output[0m [0;34m+=[0m [0mtext_result[0m[0;34m[0m[0;34m[0m[0m
[1;32m    945[0m                 [0;32mif[0m [0mvisible[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/dsc/lib/python3.7/site-packages/rpy2/ipython/rmagic.py[0m in [0;36meval[0;34m(self, code)[0m
[1;32m    406[0m                 [0mwarning_or_other_msg[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mflush[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    407[0m                 raise RInterpreterError(code, str(exception),
[0;32m--> 408[0;31m                                         warning_or_other_msg)
[0m[1;32m    409[0m             [0;32mfinally[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    410[0m                 [0mro[0m[0;34m.[0m[0m_print_deferred_warnings[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mRInterpreterError[0m: Failed to parse and evaluate line 'library(klaR)\nfeature.names.tg<-gsub("â€™", "\'", feature.names.tg)\ncolnames(feature.table.tg)<-feature.names.tg\nvars<-stepclass(feature.table.tg, metadata.table.tg[,1], method="lda", improvement=0.0001)\n'.
R error message: "Error in str2lang(x) : <text>:1:42: unexpected INCOMPLETE_STRING\n1: metadata.table.tg[, 1] ~  i + me+ an+ he+'t +e w+ ca+ou +wha+ do+ al\n                                             ^"
R stdout:
 `stepwise classification', using 10-fold cross-validated correctness rate of method lda'.
460 observations of 75 variables in 2 classes; direction: both
stop criterion: improvement less than 0.01%.
Error in str2lang(x) : <text>:1:42: unexpected INCOMPLETE_STRING
1: metadata.table.tg[, 1] ~  i + me+ an+ he+'t +e w+ ca+ou +wha+ do+ al
                                             ^
RInterpreterError: Failed to parse and evaluate line 'library(klaR)\nfeature.names.tg<-gsub("â€™", "\'", feature.names.tg)\ncolnames(feature.table.tg)<-feature.names.tg\nvars<-stepclass(feature.table.tg, metadata.table.tg[,1], method="lda", improvement=0.0001)\n'.
R error message: "Error in str2lang(x) : <text>:1:42: unexpected INCOMPLETE_STRING\n1: metadata.table.tg[, 1] ~  i + me+ an+ he+'t +e w+ ca+ou +wha+ do+ al\n                                             ^"
R stdout:
 `stepwise classification', using 10-fold cross-validated correctness rate of method lda'.
460 observations of 75 variables in 2 classes; direction: both
stop criterion: improvement less than 0.01%.
Error in str2lang(x) : <text>:1:42: unexpected INCOMPLETE_STRING
1: metadata.table.tg[, 1] ~  i + me+ an+ he+'t +e w+ ca+ou +wha+ do+ al
                                             ^

