Traceback (most recent call last):
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/qad/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Define directory for a single run's samples from the Google Colab notebook
runfiles = '/Users/qad/Downloads/ch2samples_run5'
#Change to that directory
os.chdir(runfiles)
#For each file in that directory...
for file in os.listdir(runfiles):
    #Prefix it with the run number, and suffix with the file extension
    os.rename(file, 'run5_' + file + '.txt')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-6-89af4b55ecf1>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mrunfiles[0m [0;34m=[0m [0;34m'/Users/qad/Downloads/ch2samples_run5'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m#Change to that directory[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mos[0m[0;34m.[0m[0mchdir[0m[0;34m([0m[0mrunfiles[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;31m#For each file in that directory...[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;32mfor[0m [0mfile[0m [0;32min[0m [0mos[0m[0;34m.[0m[0mlistdir[0m[0;34m([0m[0mrunfiles[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/qad/Downloads/ch2samples_run5'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/qad/Downloads/ch2samples_run5'

