Traceback (most recent call last):
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/qad/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/qad/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Sort all the files in the directory you specified above, alphabetically.
#For each of those files...
for filename in sorted(os.listdir(filedirectory)):
    #If the filename ends with .txt (i.e. if it's actually a text files)
    if filename.endswith('.txt'):
        #Write out below the name of the file
        print(filename)
        #The file name of the output file adds _ner_per to the end of the file name of the input file
        outfilename = filename.replace('.txt', '_ner_per.txt')
        #Open the input filename
        with open(filename, 'r') as f:
            #Create and open the output filename
            with open(outfilename, 'w') as out:
                #Read the contents of the input file
                chaptertext = f.read()
                #Do French NLP on the contents of the input file
                chapterner = frnlp(chaptertext)
                #For each recognized entity
                for ent in chapterner.ents:
                    #If that entity is labeled as a person
                    if ent.label_ == 'PER':
                        #Print the entity, and the label (which should be PER)
                        print(ent.text, ent.label_)
                        #Write the entity to the output file
                        out.write(ent.text)
                        #Write a newline character to the output file
                        out.write('\n')
            
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-7-a9f4cbae4497>[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m         [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m             [0;31m#Create and open the output filename[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m             [0;32mwith[0m [0mopen[0m[0;34m([0m[0moutfilename[0m[0;34m,[0m [0;34m'w'[0m[0;34m)[0m [0;32mas[0m [0mout[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m                 [0;31m#Read the contents of the input file[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m                 [0mchaptertext[0m [0;34m=[0m [0mf[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: [Errno 63] File name too long: '016_01_bg_ner_loc_ner_loc_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per.txt'
OSError: [Errno 63] File name too long: '016_01_bg_ner_loc_ner_loc_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per_ner_per.txt'

